name: Secrets and Environment Variables

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Access Repository Secrets
        env:
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

        run: |
          echo "Spotify Redirect URI: $REDIRECT_URI"
          echo "Spotify Client Secret: $CLIENT_SECRET"
          echo "Spotify Client ID: $CLIENT_ID"
